"use strict";
/**
 * Stub types for Firebase Data Connect SDK
 *
 * In production, this file would be auto-generated by Firebase Data Connect.
 * For Vercel builds where Data Connect isn't available, we provide stubs
 * that throw helpful errors at runtime.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.listEmbeddings = listEmbeddings;
exports.getJobEmbeddings = getJobEmbeddings;
exports.deleteJobEmbeddings = deleteJobEmbeddings;
/**
 * List embeddings - stub that throws when Data Connect unavailable
 */
async function listEmbeddings(_params) {
    throw new Error("Firebase Data Connect is not configured. " +
        "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
        "or use raw SQL queries for embedding operations.");
}
/**
 * Get embeddings for a specific job - stub
 */
async function getJobEmbeddings(_params) {
    throw new Error("Firebase Data Connect is not configured. " +
        "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
        "or use raw SQL queries for embedding operations.");
}
/**
 * Delete embeddings for a job - stub
 */
async function deleteJobEmbeddings(_params) {
    throw new Error("Firebase Data Connect is not configured. " +
        "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
        "or use raw SQL queries for embedding operations.");
}
//# sourceMappingURL=index.js.map