/**
 * Stub types for Firebase Data Connect SDK
 *
 * In production, this file would be auto-generated by Firebase Data Connect.
 * For Vercel builds where Data Connect isn't available, we provide stubs
 * that throw helpful errors at runtime.
 */

// Type definitions matching expected Data Connect schema
export interface VideoEmbedding {
  id: string;
  segmentType: string;
  segmentIndex: number;
  content: string;
  job?: {
    id: string;
    title?: string;
    videoUrl?: string;
  };
}

export interface ListEmbeddingsResponse {
  data: {
    videoEmbeddings: VideoEmbedding[];
  };
}

export interface GetJobEmbeddingsResponse {
  data: {
    videoEmbeddings: VideoEmbedding[];
  };
}

// UUID type for job IDs
type UUID = `${string}-${string}-${string}-${string}-${string}`;

/**
 * List embeddings - stub that throws when Data Connect unavailable
 */
export async function listEmbeddings(_params: {
  limit: number;
}): Promise<ListEmbeddingsResponse> {
  throw new Error(
    "Firebase Data Connect is not configured. " +
      "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
      "or use raw SQL queries for embedding operations."
  );
}

/**
 * Get embeddings for a specific job - stub
 */
export async function getJobEmbeddings(_params: {
  jobId: UUID;
}): Promise<GetJobEmbeddingsResponse> {
  throw new Error(
    "Firebase Data Connect is not configured. " +
      "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
      "or use raw SQL queries for embedding operations."
  );
}

/**
 * Delete embeddings for a job - stub
 */
export async function deleteJobEmbeddings(_params: {
  jobId: UUID;
}): Promise<void> {
  throw new Error(
    "Firebase Data Connect is not configured. " +
      "Run 'firebase dataconnect:sdk:generate' to generate the SDK, " +
      "or use raw SQL queries for embedding operations."
  );
}
