/**
 * Stub types for Firebase Data Connect SDK
 *
 * The real SDK is generated by `firebase dataconnect:sdk:generate`.
 * These stubs allow the package to compile independently.
 */

type UUID = `${string}-${string}-${string}-${string}-${string}`;

interface VideoEmbeddingRow {
  id: string;
  segmentType: string;
  segmentIndex: number;
  content: string;
  createdAt: string;
  job?: {
    id: string;
    title?: string;
    videoUrl?: string;
  };
}

interface ListEmbeddingsResponse {
  data: { videoEmbeddings: VideoEmbeddingRow[] };
}

interface GetJobEmbeddingsResponse {
  data: { videoEmbeddings: VideoEmbeddingRow[] };
}

interface DeleteJobEmbeddingsResponse {
  data: { videoEmbedding_deleteMany: number };
}

export declare function listEmbeddings(vars: {
  limit: number;
}): Promise<ListEmbeddingsResponse>;

export declare function getJobEmbeddings(vars: {
  jobId: UUID;
}): Promise<GetJobEmbeddingsResponse>;

export declare function deleteJobEmbeddings(vars: {
  jobId: UUID;
}): Promise<DeleteJobEmbeddingsResponse>;
