/**
 * Stub types for Firebase Data Connect SDK
 *
 * In production, this file would be auto-generated by Firebase Data Connect.
 * For Vercel builds where Data Connect isn't available, we provide stubs
 * that throw helpful errors at runtime.
 */
export interface VideoEmbedding {
    id: string;
    segmentType: string;
    segmentIndex: number;
    content: string;
    job?: {
        id: string;
        title?: string;
        videoUrl?: string;
    };
}
export interface ListEmbeddingsResponse {
    data: {
        videoEmbeddings: VideoEmbedding[];
    };
}
export interface GetJobEmbeddingsResponse {
    data: {
        videoEmbeddings: VideoEmbedding[];
    };
}
type UUID = `${string}-${string}-${string}-${string}-${string}`;
/**
 * List embeddings - stub that throws when Data Connect unavailable
 */
export declare function listEmbeddings(_params: {
    limit: number;
}): Promise<ListEmbeddingsResponse>;
/**
 * Get embeddings for a specific job - stub
 */
export declare function getJobEmbeddings(_params: {
    jobId: UUID;
}): Promise<GetJobEmbeddingsResponse>;
/**
 * Delete embeddings for a job - stub
 */
export declare function deleteJobEmbeddings(_params: {
    jobId: UUID;
}): Promise<void>;
export {};
//# sourceMappingURL=index.d.ts.map