
kind: ClusterRole
metadata:
  name: gmp-operator-fix
rules:
- apiGroups: ["monitoring.googleapis.com"]
  resources: ["clusterpodmonitorings"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gmp-operator-fix-binding
subjects:
- kind: ServiceAccount
  name: operator
  namespace: gke-gmp-system
roleRef:
  kind: ClusterRole
  name: gmp-operator-fix
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ray-operator-fix
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-operator-fix-binding
subjects:
- kind: User
  name: system:kuberay-operator
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ray-operator-fix
  apiGroup: rbac.authorization.k8s.io
