/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6250fc3db1ced95552581f373e492e74)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/groupthinking/netmesh";
		DISPATCH_NAMESPACE: "uvai";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "uvai";
		CUSTOM_DOMAIN: "uvai.io";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		GROQ_API_KEY: string;
		XAI_API_KEY: string;
		PERPLEXITY_API_KEY: string;
		JWT_SECRET: string;
		WEBHOOK_SECRET: string;
		SECRETS_ENCRYPTION_KEY: string;
		ALLOWED_EMAIL: string;
		VITE_MCP_BRIDGE_URL: string;
		VITE_ORCHESTRATOR_URL: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		ML_EXPERIMENTS_DB: D1Database;
		UVAI_DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		VECTORIZE: VectorizeIndex;
		AI: Ai;
		IMAGES: ImagesBinding;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
		VECTOR_WORKFLOW: Workflow;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "CUSTOM_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "GOOGLE_AI_STUDIO_API_KEY" | "GROQ_API_KEY" | "XAI_API_KEY" | "PERPLEXITY_API_KEY" | "JWT_SECRET" | "WEBHOOK_SECRET" | "SECRETS_ENCRYPTION_KEY" | "ALLOWED_EMAIL" | "VITE_MCP_BRIDGE_URL" | "VITE_ORCHESTRATOR_URL">> {}
}
