import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    NEXT_PUBLIC_SUPABASE_URL: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    DIRECT_URL: z.ZodOptional<z.ZodString>;
    XAI_API_KEY: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    GOOGLE_GENERATIVE_AI_API_KEY: z.ZodOptional<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_APP_URL: z.ZodOptional<z.ZodString>;
    NEXTAUTH_SECRET: z.ZodOptional<z.ZodString>;
    NEXTAUTH_URL: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    OPENAI_API_KEY?: string | undefined;
    NEXT_PUBLIC_SUPABASE_URL?: string | undefined;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    DATABASE_URL?: string | undefined;
    DIRECT_URL?: string | undefined;
    XAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    GOOGLE_GENERATIVE_AI_API_KEY?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    NEXT_PUBLIC_APP_URL?: string | undefined;
    NEXTAUTH_SECRET?: string | undefined;
    NEXTAUTH_URL?: string | undefined;
}, {
    OPENAI_API_KEY?: string | undefined;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    NEXT_PUBLIC_SUPABASE_URL?: string | undefined;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    DATABASE_URL?: string | undefined;
    DIRECT_URL?: string | undefined;
    XAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    GOOGLE_GENERATIVE_AI_API_KEY?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    NEXT_PUBLIC_APP_URL?: string | undefined;
    NEXTAUTH_SECRET?: string | undefined;
    NEXTAUTH_URL?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare const env: {
    NODE_ENV: "development" | "production" | "test";
    OPENAI_API_KEY?: string | undefined;
    NEXT_PUBLIC_SUPABASE_URL?: string | undefined;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    DATABASE_URL?: string | undefined;
    DIRECT_URL?: string | undefined;
    XAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    GOOGLE_GENERATIVE_AI_API_KEY?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    NEXT_PUBLIC_APP_URL?: string | undefined;
    NEXTAUTH_SECRET?: string | undefined;
    NEXTAUTH_URL?: string | undefined;
};
export declare const isDevelopment: boolean;
export declare const isProduction: boolean;
export declare const isTest: boolean;
export {};
