"""
Evolutionary Memory - Persistent Tool Storage

The "Self-Morphing" agent needs a place to store the tools it builds
and the lessons it learns. This module provides:
1. ToolRepository: Saves generated code to disk
2. Hot-loading of evolved tools
3. (Future) Vector indexing for semantic search
"""

import os
import glob
import json
from datetime import datetime
from typing import List, Dict, Any, Optional

# Storage directories
TOOL_STORAGE_DIR = os.path.join(os.path.dirname(__file__), "evolved_tools")
MEMORY_INDEX_FILE = os.path.join(TOOL_STORAGE_DIR, "_index.json")

# Ensure storage exists
os.makedirs(TOOL_STORAGE_DIR, exist_ok=True)


def load_memory_index() -> Dict[str, Any]:
    """Load the memory index file"""
    if os.path.exists(MEMORY_INDEX_FILE):
        with open(MEMORY_INDEX_FILE, "r") as f:
            return json.load(f)
    return {"tools": {}, "lessons": [], "created_at": datetime.now().isoformat()}


def save_memory_index(index: Dict[str, Any]) -> None:
    """Save the memory index file"""
    index["updated_at"] = datetime.now().isoformat()
    with open(MEMORY_INDEX_FILE, "w") as f:
        json.dump(index, f, indent=2)


def load_evolved_tools() -> List[Any]:
    """
    Scans the storage directory and hot-loads all Python tools found there.
    Returns a list of instantiated tool objects.
    """
    tools = []

    for filepath in glob.glob(f"{TOOL_STORAGE_DIR}/*.py"):
        if filepath.endswith("__init__.py"):
            continue

        try:
            with open(filepath, "r") as f:
                code = f.read()

            # Dynamic import - use with caution
            local_scope = {"__name__": os.path.basename(filepath)}
            exec(code, globals(), local_scope)

            # Look for classes that inherit from Tool
            for name, obj in local_scope.items():
                if (
                    isinstance(obj, type)
                    and name not in ("Tool", "EvolvedTool")
                    and hasattr(obj, "forward")
                ):
                    tools.append(obj())
                    print(f"🧠 Loaded evolved tool: {name}")

        except Exception as e:
            print(f"⚠️  Failed to load {filepath}: {e}")

    return tools


def save_new_tool(code: str, tool_name: str, description: str = "") -> str:
    """
    Persists a newly created tool to the 'Brain'.

    Args:
        code: The Python source code of the tool
        tool_name: A unique name for the tool (will become filename)
        description: Optional description of what the tool does

    Returns:
        The filepath where the tool was saved
    """
    # Sanitize tool name
    safe_name = "".join(c if c.isalnum() or c == "_" else "_" for c in tool_name)
    filepath = os.path.join(TOOL_STORAGE_DIR, f"{safe_name}.py")

    # Add header comment
    header = f'''"""
Evolved Tool: {tool_name}
Created: {datetime.now().isoformat()}
Description: {description or 'Auto-generated by Prescient Twin agent'}
"""

'''

    with open(filepath, "w") as f:
        f.write(header + code)

    # Update index
    index = load_memory_index()
    index["tools"][tool_name] = {
        "filepath": filepath,
        "created_at": datetime.now().isoformat(),
        "description": description,
        "uses": 0,
    }
    save_memory_index(index)

    print(f"🧠 Evolution Saved: {tool_name} is now permanent at {filepath}")
    return filepath


def record_lesson(lesson: str, context: Optional[Dict[str, Any]] = None) -> None:
    """
    Record a lesson learned by the agent for future reference.
    """
    index = load_memory_index()
    index["lessons"].append(
        {
            "lesson": lesson,
            "context": context or {},
            "timestamp": datetime.now().isoformat(),
        }
    )
    save_memory_index(index)
    print(f"📚 Lesson Recorded: {lesson[:50]}...")


def get_lessons(limit: int = 10) -> List[Dict[str, Any]]:
    """Retrieve recent lessons"""
    index = load_memory_index()
    return index.get("lessons", [])[-limit:]


def get_tool_stats() -> Dict[str, Any]:
    """Get statistics about evolved tools"""
    index = load_memory_index()
    return {
        "total_tools": len(index.get("tools", {})),
        "total_lessons": len(index.get("lessons", [])),
        "tools": list(index.get("tools", {}).keys()),
    }


# Quick test
if __name__ == "__main__":
    print("🧠 Memory Module Test")
    print(f"Storage: {TOOL_STORAGE_DIR}")

    # Test saving a tool
    test_code = """
from smolagents import Tool

class TestCalculator(Tool):
    name = "calculator"
    description = "A simple calculator"
    inputs = {"expression": {"type": "string", "description": "Math expression"}}
    output_type = "string"

    def forward(self, expression: str) -> str:
        try:
            return str(eval(expression))
        except:
            return "Error"
"""
    save_new_tool(test_code, "TestCalculator", "A test calculator tool")
    record_lesson("Tools can be dynamically created and loaded")

    print(f"\nStats: {get_tool_stats()}")
