extend type Mutation {
  """
  ✨ Insert a single `JobEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  jobEvent_insert(
    """
    Data object to insert into the table.
    """
    data: JobEvent_Data!
  ): JobEvent_KeyOutput! @fdc_generated(from: "JobEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `VideoEmbedding` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoEmbedding_insert(
    """
    Data object to insert into the table.
    """
    data: VideoEmbedding_Data!
  ): VideoEmbedding_KeyOutput! @fdc_generated(from: "VideoEmbedding", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `VideoJob` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoJob_insert(
    """
    Data object to insert into the table.
    """
    data: VideoJob_Data!
  ): VideoJob_KeyOutput! @fdc_generated(from: "VideoJob", purpose: INSERT_SINGLE)
  """
  ✨ Insert `JobEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  jobEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [JobEvent_Data!]!
  ): [JobEvent_KeyOutput!]! @fdc_generated(from: "JobEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `VideoEmbedding` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoEmbedding_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [VideoEmbedding_Data!]!
  ): [VideoEmbedding_KeyOutput!]! @fdc_generated(from: "VideoEmbedding", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `VideoJob` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoJob_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [VideoJob_Data!]!
  ): [VideoJob_KeyOutput!]! @fdc_generated(from: "VideoJob", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `JobEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `JobEvent`.
  """
  jobEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: JobEvent_Data!
  ): JobEvent_KeyOutput! @fdc_generated(from: "JobEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `VideoEmbedding` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoEmbedding`.
  """
  videoEmbedding_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: VideoEmbedding_Data!
  ): VideoEmbedding_KeyOutput! @fdc_generated(from: "VideoEmbedding", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `VideoJob` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoJob`.
  """
  videoJob_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: VideoJob_Data!
  ): VideoJob_KeyOutput! @fdc_generated(from: "VideoJob", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `JobEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `JobEvent`.
  """
  jobEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [JobEvent_Data!]!
  ): [JobEvent_KeyOutput!]! @fdc_generated(from: "JobEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `VideoEmbedding` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoEmbedding`.
  """
  videoEmbedding_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [VideoEmbedding_Data!]!
  ): [VideoEmbedding_KeyOutput!]! @fdc_generated(from: "VideoEmbedding", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `VideoJob` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoJob`.
  """
  videoJob_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [VideoJob_Data!]!
  ): [VideoJob_KeyOutput!]! @fdc_generated(from: "VideoJob", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `JobEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `JobEvent` or `null` if not found.
  """
  jobEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: JobEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: JobEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: JobEvent_Data!
  ): JobEvent_KeyOutput @fdc_generated(from: "JobEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `VideoEmbedding` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `VideoEmbedding` or `null` if not found.
  """
  videoEmbedding_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoEmbedding_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoEmbedding_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: VideoEmbedding_Data!
  ): VideoEmbedding_KeyOutput @fdc_generated(from: "VideoEmbedding", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `VideoJob` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `VideoJob` or `null` if not found.
  """
  videoJob_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoJob_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: VideoJob_Data!
  ): VideoJob_KeyOutput @fdc_generated(from: "VideoJob", purpose: UPDATE_SINGLE)
  """
  ✨ Update `JobEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  jobEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: JobEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: JobEvent_Data!
  ): Int! @fdc_generated(from: "JobEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `VideoEmbedding` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  videoEmbedding_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: VideoEmbedding_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: VideoEmbedding_Data!
  ): Int! @fdc_generated(from: "VideoEmbedding", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `VideoJob` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  videoJob_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: VideoJob_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: VideoJob_Data!
  ): Int! @fdc_generated(from: "VideoJob", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `JobEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  jobEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: JobEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: JobEvent_FirstRow
  ): JobEvent_KeyOutput @fdc_generated(from: "JobEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `VideoEmbedding` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  videoEmbedding_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoEmbedding_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoEmbedding_FirstRow
  ): VideoEmbedding_KeyOutput @fdc_generated(from: "VideoEmbedding", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `VideoJob` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  videoJob_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoJob_FirstRow
  ): VideoJob_KeyOutput @fdc_generated(from: "VideoJob", purpose: DELETE_SINGLE)
  """
  ✨ Delete `JobEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  jobEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: JobEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `VideoEmbedding` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  videoEmbedding_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: VideoEmbedding_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `VideoJob` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  videoJob_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: VideoJob_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob", purpose: DELETE_MULTIPLE)
}
