extend type JobEvent {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "JobEvent", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `JobEvent` table.
  """
  _count: Int! @fdc_generated(from: "JobEvent.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `agent` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  agent_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.agent", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `eventType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  eventType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.eventType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `jobId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  jobId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.jobId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `JobEvent` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "JobEvent.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `JobEvent` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "JobEvent.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `JobEvent` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "JobEvent.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "JobEvent.id", purpose: GLOBAL_ID)
}
extend type VideoEmbedding {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "VideoEmbedding", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table.
  """
  _count: Int! @fdc_generated(from: "VideoEmbedding.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `embedding` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  embedding_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.embedding", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `jobId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  jobId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.jobId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `segmentIndex` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  segmentIndex_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.segmentIndex", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoEmbedding` table where the `segmentType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  segmentType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoEmbedding.segmentType", purpose: QUERY_COUNT)
  """
  ✨ Sum the `segmentIndex` field in the `VideoEmbedding` table.
  """
  segmentIndex_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VideoEmbedding.segmentIndex", purpose: QUERY_SUM)
  """
  ✨ Average the `segmentIndex` field in the `VideoEmbedding` table.
  """
  segmentIndex_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VideoEmbedding.segmentIndex", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `VideoEmbedding` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "VideoEmbedding.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `segmentIndex` field in the `VideoEmbedding` table.
  """
  segmentIndex_min: Int @fdc_generated(from: "VideoEmbedding.segmentIndex", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `VideoEmbedding` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "VideoEmbedding.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `segmentIndex` field in the `VideoEmbedding` table.
  """
  segmentIndex_max: Int @fdc_generated(from: "VideoEmbedding.segmentIndex", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "VideoEmbedding.id", purpose: GLOBAL_ID)
}
extend type VideoJob {
  """
  ✨ List `JobEvent` objects in a one-to-many relationship (where `JobEvent`.`job` is this object).
  """
  jobEvents_on_job(
    """
    Filter condition to narrow down the query results.
    """
    where: JobEvent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [JobEvent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: JobEvent_Having
  ): [JobEvent!]! @fdc_generated(from: "JobEvent.job", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `VideoEmbedding` objects in a one-to-many relationship (where `VideoEmbedding`.`job` is this object).
  """
  videoEmbeddings_on_job(
    """
    Filter condition to narrow down the query results.
    """
    where: VideoEmbedding_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VideoEmbedding_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VideoEmbedding_Having
  ): [VideoEmbedding!]! @fdc_generated(from: "VideoEmbedding.job", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "VideoJob", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `VideoJob` table.
  """
  _count: Int! @fdc_generated(from: "VideoJob.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `duration` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  duration_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.duration", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `error` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  error_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.error", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `fileSize` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileSize_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.fileSize", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `resultJson` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  resultJson_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.resultJson", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `source` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  source_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.source", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `taskType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  taskType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.taskType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoJob` table where the `videoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  videoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoJob.videoUrl", purpose: QUERY_COUNT)
  """
  ✨ Sum the `duration` field in the `VideoJob` table.
  """
  duration_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VideoJob.duration", purpose: QUERY_SUM)
  """
  ✨ Sum the `fileSize` field in the `VideoJob` table.
  """
  fileSize_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VideoJob.fileSize", purpose: QUERY_SUM)
  """
  ✨ Average the `duration` field in the `VideoJob` table.
  """
  duration_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VideoJob.duration", purpose: QUERY_AVG)
  """
  ✨ Average the `fileSize` field in the `VideoJob` table.
  """
  fileSize_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VideoJob.fileSize", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `VideoJob` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "VideoJob.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `duration` field in the `VideoJob` table.
  """
  duration_min: Int @fdc_generated(from: "VideoJob.duration", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fileSize` field in the `VideoJob` table.
  """
  fileSize_min: Int @fdc_generated(from: "VideoJob.fileSize", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `VideoJob` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "VideoJob.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `VideoJob` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "VideoJob.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `duration` field in the `VideoJob` table.
  """
  duration_max: Int @fdc_generated(from: "VideoJob.duration", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fileSize` field in the `VideoJob` table.
  """
  fileSize_max: Int @fdc_generated(from: "VideoJob.fileSize", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `VideoJob` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "VideoJob.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "VideoJob.id", purpose: GLOBAL_ID)
}
