import os
import json
import glob
from typing import Dict, Any

ROOT_DIR = os.getcwd()
CATALOG_FILE = os.path.join(ROOT_DIR, "shared/PROJECT_CATALOG.md")

def get_project_info(path: str) -> Dict[str, Any]:
    info = {
        "name": os.path.basename(path),
        "path": os.path.relpath(path, ROOT_DIR),
        "type": "Unknown",
        "stack": "Unknown",
        "desc": ""
    }

    # Check Node.js
    pkg_json = os.path.join(path, "package.json")
    if os.path.exists(pkg_json):
        try:
            with open(pkg_json, 'r') as f:
                data = json.load(f)
                info["name"] = data.get("name", info["name"])
                info["desc"] = data.get("description", "")
                deps = data.get("dependencies", {})
                frameworks = []
                if "react" in deps: frameworks.append(f"React {deps['react']}")
                if "next" in deps: frameworks.append(f"Next.js {deps['next']}")
                if "vite" in deps: frameworks.append(f"Vite {deps['vite']}")
                if "express" in deps: frameworks.append(f"Express {deps['express']}")
                if "@modelcontextprotocol/sdk" in deps: info["type"] = "MCP Server"

                # Check devDeps for TS
                dev_deps = data.get("devDependencies", {})
                if "typescript" in dev_deps:
                    frameworks.append(f"TS {dev_deps['typescript']}")

                info["stack"] = f"Node.js ({', '.join(frameworks)})" if frameworks else "Node.js"
        except:
            pass

    # Check Python
    if glob.glob(os.path.join(path, "*.py")) or os.path.exists(os.path.join(path, "pyproject.toml")) or os.path.exists(os.path.join(path, "requirements.txt")):
        if info["stack"] == "Unknown":
            info["stack"] = "Python"
        else:
            info["stack"] += " / Python"

        if os.path.exists(os.path.join(path, "pyproject.toml")):
             info["stack"] += " (Poetry/PDM)"

    # Heuristics
    if "mcp-servers" in path:
        info["type"] = "MCP Server"
    elif "projects" in path:
        info["type"] = "Project"

    return info

def main() -> None:
    projects = []

    # Scan locations
    scan_paths = [
        "projects/*",
        "mcp-servers/*",
        "agents-marketplace",
        "xai-grok-wrapper",
        "backend",
        "apps/*",
        "packages/*"
    ]

    for pattern in scan_paths:
        for path in glob.glob(pattern):
            if os.path.isdir(path):
                projects.append(get_project_info(path))

    # Generate Markdown
    md = "# Project Catalog\n\nGenerated by Autonomous Agent.\n\n"
    md += "| Name | Path | Type | Stack | Description |\n"
    md += "|------|------|------|-------|-------------|\n"

    for p in sorted(projects, key=lambda x: x['path']):
        md += f"| {p['name']} | `{p['path']}` | {p['type']} | {p['stack']} | {p['desc']} |\n"

    os.makedirs(os.path.dirname(CATALOG_FILE), exist_ok=True)
    with open(CATALOG_FILE, 'w') as f:
        f.write(md)

    print(f"Catalog generated at {CATALOG_FILE}")

if __name__ == "__main__":
    main()
