"""Action Priority Ranker — Model #2.

Ranks actions generated by the agent orchestrator by relevance,
actionability, and user value. Allows the platform to surface the
highest-impact actions first.

Features used:
    - Action text (specificity, length, verb strength)
    - Action type (task, insight, recommendation, warning)
    - Video context (category, duration, engagement)
    - Actionability signals (has URL, has deadline, has metric)

Output:
    - priority_score: 0.0 – 1.0
    - tier: "critical" | "high" | "medium" | "low"
    - reasoning: explanation of ranking
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class ActionTier(str, Enum):
    """Priority tiers for ranked actions."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class RankedAction:
    """A single action with its priority score and metadata."""

    original_text: str
    priority_score: float
    tier: ActionTier
    reasoning: str
    features: dict[str, float] = field(default_factory=dict)
    original_index: int = 0


@dataclass
class RankingResult:
    """Full ranking output for a set of actions."""

    ranked_actions: list[RankedAction]
    total_actions: int
    processing_time_seconds: float
    model_version: str


class ActionPriorityRanker:
    """Scores and ranks generated actions by impact and actionability.

    Phase 1: NLP heuristics (verb strength, specificity, presence of metrics).
    Phase 2: Fine-tuned embeddings from user feedback
    (click-through, completion).
    """

    # Strong action verbs → higher priority
    STRONG_VERBS: set[str] = {
        "implement", "build", "create", "deploy", "launch", "fix", "resolve",
        "migrate", "refactor", "automate", "integrate", "optimize", "secure",
        "test", "validate", "monitor", "scale", "upgrade",
    }

    MEDIUM_VERBS: set[str] = {
        "review", "evaluate", "assess", "analyze", "consider", "explore",
        "investigate", "plan", "design", "draft", "research", "compare",
    }

    WEAK_VERBS: set[str] = {
        "think", "note", "remember", "keep", "maybe", "might", "could",
        "possibly", "perhaps", "someday",
    }

    # Specificity indicators
    SPECIFICITY_PATTERNS: list[tuple[str, float]] = [
        (r"\d+%", 0.08),           # Contains percentage
        (r"\$[\d,]+", 0.10),       # Contains dollar amount
        (r"\d+ (day|week|month|hour)", 0.07),  # Contains timeline
        (r"https?://\S+", 0.06),   # Contains URL
        (r"\b(API|SDK|CLI|UI|UX)\b", 0.05),  # Contains tech reference
        (r"\b(KPI|ROI|MRR|ARR|NPS)\b", 0.08),  # Contains business metric
        (r"\b(by|before|deadline|due)\b", 0.06),  # Contains deadline language
        (r"step \d|phase \d", 0.05),  # Contains step/phase reference
    ]

    def __init__(self) -> None:
        self._training_samples: int = 0
        self._version: str = "1.0.0-heuristic"
        self._verb_feedback_weights: dict[str, float] = {}
        self._global_feedback_bias: float = 0.0

    def rank(
        self,
        actions: list[str | dict[str, Any]],
        video_context: dict[str, Any] | None = None,
    ) -> RankingResult:
        """Rank a list of actions by priority.

        Args:
            actions: Raw action strings or action dicts from orchestrator.
            video_context: Optional video metadata for contextual boosting.

        Returns:
            RankingResult with sorted actions.
        """

        start_time = time.monotonic()

        scored_actions: list[RankedAction] = []

        for idx, action in enumerate(actions):
            if isinstance(action, dict):
                text = str(
                    action.get("text")
                    or action.get("action")
                    or action.get("description")
                    or ""
                )
                action_type = str(
                    action.get("type")
                    or action.get("category")
                    or ""
                )
            else:
                text = str(action)
                action_type = ""

            if not text.strip():
                continue

            score, features = self._score_action(
                text, action_type, video_context,
            )
            tier = self._score_to_tier(score)
            reasoning = self._build_reasoning(text, features, tier)

            scored_actions.append(
                RankedAction(
                    original_text=text,
                    priority_score=round(score, 4),
                    tier=tier,
                    reasoning=reasoning,
                    features=features,
                    original_index=idx,
                )
            )

        # Sort by priority (highest first)
        scored_actions.sort(key=lambda a: a.priority_score, reverse=True)

        elapsed = time.monotonic() - start_time

        return RankingResult(
            ranked_actions=scored_actions,
            total_actions=len(scored_actions),
            processing_time_seconds=round(elapsed, 4),
            model_version=self._version,
        )

    def _score_action(
        self,
        text: str,
        action_type: str,
        video_context: dict[str, Any] | None,
    ) -> tuple[float, dict[str, float]]:
        """Compute priority score for a single action."""

        features: dict[str, float] = {}
        text_lower = text.lower().strip()
        words = text_lower.split()

        # --- Verb strength ---
        first_verb = words[0] if words else ""
        if first_verb in self.STRONG_VERBS:
            features["verb_strength"] = 0.20
        elif first_verb in self.MEDIUM_VERBS:
            features["verb_strength"] = 0.10
        elif first_verb in self.WEAK_VERBS:
            features["verb_strength"] = -0.05
        else:
            # Check whole text for strong verbs
            has_strong = any(v in text_lower for v in self.STRONG_VERBS)
            features["verb_strength"] = 0.10 if has_strong else 0.0
        features["learned_feedback"] = self._global_feedback_bias + self._verb_feedback_weights.get(
            first_verb,
            0.0,
        )

        # --- Specificity (regex patterns) ---
        specificity_total = 0.0
        for pattern, weight in self.SPECIFICITY_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                specificity_total += weight
        features["specificity"] = min(specificity_total, 0.25)

        # --- Length signal ---
        # Too short = vague, too long = unfocused. Sweet spot: 10-50 words
        word_count = len(words)
        if 10 <= word_count <= 50:
            features["length"] = 0.05
        elif word_count < 5:
            features["length"] = -0.10
        elif word_count > 100:
            features["length"] = -0.05
        else:
            features["length"] = 0.0

        # --- Actionability ---
        # Does it tell you WHAT to do, not just WHAT happened?
        passive_indicators = {
            "was", "were", "has been",
            "is being", "noted", "observed",
        }
        is_passive = any(
            ind in text_lower for ind in passive_indicators
        )
        features["actionability"] = -0.10 if is_passive else 0.05

        # --- Business impact language ---
        impact_words = {
            "revenue", "cost", "user", "customer",
            "growth", "retention", "conversion", "churn",
        }
        has_impact = any(w in text_lower for w in impact_words)
        features["business_impact"] = 0.10 if has_impact else 0.0

        # --- Urgency signals ---
        urgency_words = {
            "immediately", "urgent", "critical",
            "asap", "breaking", "blocker", "now",
        }
        has_urgency = any(w in text_lower for w in urgency_words)
        features["urgency"] = 0.15 if has_urgency else 0.0

        # --- Action type boost ---
        if action_type.lower() in {"task", "action_item", "todo"}:
            features["type_boost"] = 0.05
        elif action_type.lower() in {"insight", "observation"}:
            features["type_boost"] = -0.03
        else:
            features["type_boost"] = 0.0

        # --- Video context boost ---
        if video_context:
            view_count = int(video_context.get("view_count") or 0)
            if view_count > 1_000_000:
                features["viral_context"] = 0.05
            category = str(video_context.get("category") or "")
            if category.lower() in {"education", "science", "technology"}:
                features["category_boost"] = 0.03

        # Compute final score
        base_score = 0.50  # Neutral baseline
        raw_score = base_score + sum(features.values())
        final_score = max(0.0, min(1.0, raw_score))

        return final_score, features

    @staticmethod
    def _score_to_tier(score: float) -> ActionTier:
        """Map a numeric score to a named tier."""

        if score >= 0.80:
            return ActionTier.CRITICAL
        if score >= 0.65:
            return ActionTier.HIGH
        if score >= 0.45:
            return ActionTier.MEDIUM
        return ActionTier.LOW

    @staticmethod
    def _build_reasoning(
        text: str,
        features: dict[str, float],
        tier: ActionTier,
    ) -> str:
        """Human-readable explanation of the ranking."""

        reasons: list[str] = []

        if features.get("verb_strength", 0) >= 0.15:
            reasons.append("Strong action verb")
        if features.get("specificity", 0) >= 0.10:
            reasons.append("Contains specific metrics or references")
        if features.get("business_impact", 0) > 0:
            reasons.append("Business impact language detected")
        if features.get("urgency", 0) > 0:
            reasons.append("Urgency signals present")
        if features.get("actionability", 0) < 0:
            reasons.append("Passive/observational — lower actionability")
        if features.get("length", 0) < 0:
            reasons.append("Too brief or too verbose")

        if reasons:
            return "; ".join(reasons)
        return f"Standard {tier.value} priority"

    def record_feedback(
        self,
        action_text: str,
        user_clicked: bool,
        user_completed: bool,
        time_to_complete_seconds: float | None = None,
    ) -> None:
        """Record user interaction for continuous learning.

        Phase 2: This data feeds into embedding fine-tuning.
        """

        self._training_samples += 1
        normalized_text = action_text.lower().strip()
        first_word = normalized_text.split()[0] if normalized_text else ""
        target_outcome = 0.0
        if user_clicked:
            target_outcome += 0.4
        if user_completed:
            target_outcome += 0.6
        if time_to_complete_seconds and time_to_complete_seconds <= 300:
            target_outcome = min(1.0, target_outcome + 0.1)

        learning_rate = min(0.20, 1.0 / max(self._training_samples, 1) ** 0.5)
        self._global_feedback_bias = max(
            -0.10,
            min(
                0.10,
                self._global_feedback_bias
                + learning_rate * (target_outcome - 0.5) * 0.1,
            ),
        )
        if first_word:
            updated_weight = self._verb_feedback_weights.get(first_word, 0.0) + (
                learning_rate * (target_outcome - 0.5)
            )
            self._verb_feedback_weights[first_word] = max(
                -0.20,
                min(0.20, updated_weight),
            )
        self._version = "1.1.0-online"
        logger.info(
            "Action feedback sample %d: clicked=%s completed=%s verb_weight=%.4f",
            self._training_samples,
            user_clicked,
            user_completed,
            self._verb_feedback_weights.get(first_word, 0.0),
        )

    @property
    def model_info(self) -> dict[str, Any]:
        """Model metadata for monitoring."""

        return {
            "name": "ActionPriorityRanker",
            "version": self._version,
            "training_samples": self._training_samples,
            "mode": "learned" if self._training_samples > 500 else "heuristic",
            "verb_feedback_weights": dict(self._verb_feedback_weights),
        }
